services:
  - type: web
    name: esports-arena-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /health
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        value: "Host=aws-1-us-west-2.pooler.supabase.com;Port=5432;Database=postgres;Username=postgres.rzuhfopobsedxdjthwqy;Password=i948p9K12***;SSL Mode=Require;Trust Server Certificate=true"
      - key: Supabase__Url
        value: "https://rzuhfopobsedxdjthwqy.supabase.co"
      - key: Cors__AllowedOrigins
        value: "*"
